### ISSUE TITLE
Data density: allow more data to be shown in one screen

### ISSUE THREAD

**Issue by Andries-Smit** [mendix/mendix-ui-framework-lib#5]
Dear UX team, compliments for the work so far!

All the teams are based on Bootstrap. Bootstrap has a lot of spacing around forms input, labels, text etc.
However in Mendix we have built often apps that contains a lot of data that need to be shown in one form. Adjusting all the individual margins and padding is cumbersome work.

Please add a % input that influences all the padding and margins in the forms, so more data can be displayed in one form.

**Comment by Remcovh** [comment]
Hey Andries,

Thanks for your feedback. In your example do you mean the form (dataview) or the entire page? Can you maybe mail us a screenshot / app of what you want to achieve? Our email address is ux@mendix.com.

**Comment by Andries-Smit** [comment]
**low density**

Currently the density of form is low, due to lots of padding and spacing

![low density form](https://cloud.githubusercontent.com/assets/6724749/12840505/3d45ac2a-cbe4-11e5-83a3-d1839defd092.png)

**high density form**
It would be great to have a view parameter that will affect all paddings and spacing through the whole theme. 

![high density form](https://cloud.githubusercontent.com/assets/6724749/12840495/2c33b2ce-cbe4-11e5-9954-3f520dcdb0b7.png)

_Quick and dirty for this sample only._

```
.form-control {
    padding: 5px 6px !important;
    line-height: 1;
    height: 26px;
}

.form-group {
    margin-bottom: 5px;
}

.col-lg-1, .col-lg-10, .col-lg-11, .col-lg-12, .col-lg-2, .col-lg-3, .col-lg-4, .col-lg-5, .col-lg-6, .col-lg-7, .col-lg-8, .col-lg-9, .col-md-1, .col-md-10, .col-md-11, .col-md-12, .col-md-2, .col-md-3, .col-md-4, .col-md-5, .col-md-6, .col-md-7, .col-md-8, .col-md-9, .col-sm-1, .col-sm-10, .col-sm-11, .col-sm-12, .col-sm-2, .col-sm-3, .col-sm-4, .col-sm-5, .col-sm-6, .col-sm-7, .col-sm-8, .col-sm-9, .col-xs-1, .col-xs-10, .col-xs-11, .col-xs-12, .col-xs-2, .col-xs-3, .col-xs-4, .col-xs-5, .col-xs-6, .col-xs-7, .col-xs-8, .col-xs-9 {
    padding-right: 5px;
    padding-left: 5px;
}
```

**Comment by Remcovh** [comment]
Hey Andries,

Thanks you for the example. We will take a look how we can implement this in the framework.

**Comment by Remcovh** [comment]
We just did an update for all our themes with the option to customize all forms.

You can find the release notes here:
https://github.com/mendix/mendix-ui-framework-lib/releases/tag/1.0.0

Hope this helps with your issue. If you have any questions please let us know.
